### PR TITLE
Upperbound checker

### PR DESCRIPTION
**Pull request by kelloggm**

### CODE REVIEW

**Comment by smillst** [comment]
The diffs include removing the lower bound checker and do not include the MinLenChecker.  Would you please close this pull request and open this one https://github.com/kelloggm/checker-framework/compare/typetools-master...kelloggm:upperbound-checker instead?

**Comment by kelloggm** [comment]
Closed this one and opened the other:
https://github.com/typetools/checker-framework/pull/920

On Mon, Sep 19, 2016 at 3:01 PM, Suzanne Millstein <notifications@github.com

**Comment by smillst** [comment]
Did you use the link?
https://github.com/kelloggm/checker-framework/compare/typetools-master...kelloggm:upperbound-checker

You made a pull request against typetools/master, but I would like one
against kelloggm/typetools-master.

**Comment by kelloggm** [comment]
https://github.com/kelloggm/checker-framework/pull/7

Sorry, my bad.

On Mon, Sep 19, 2016 at 3:12 PM, Suzanne Millstein <notifications@github.com

**Comment by smillst** [comment]
Thanks!

**Pull request closed without merging**
